### ISSUE TITLE
Potentially change schema

### ISSUE THREAD

**Issue by hputzek** [IoTPanic/pixelpusher#3]
https://github.com/IoTPanic/pixelpusher/blob/1954a2275d911fd2c72e5671dec6ab1d9487e169/protobufs/api.proto#L40

Maybe we should allow for 1-4 color values per Pixel but not call them "rgbw"?
Because there can be the case that you want to control a "warm/cold white" device which would mean you got two color values.
Or warm/cold/amber instead of "rgb" 

Is it possible to just define it like that in the enum?:
```javascript
enum MatrixType {
    WHITE = 0;
    WARM_COLD_WHITE = 1
    WARM_COLD_AMBER = 2
    RGB = 2;
    RGBW = 3;
}
```
One more question: You could use the constants from the enum instead of the numerical values here?: 
https://github.com/IoTPanic/pixelpusher/blob/master/protobufs/api.proto#L33

This would make it more readable, so if this works I would <3 it.

**Comment by IoTPanic** [comment]
It is not per pixel, the enums define the type of matrix, could I have an example of a "warm cold device"? And the matrix value in an update is a ID for which matrix to use, the update is for changing values within the matrix, not for updating what colour lighting it uses.

**Comment by IoTPanic** [comment]
Will be called fixtures on your end.

**Comment by IoTPanic** [comment]
Update to-
```
enum MatrixType {
    WHITE = 0;
    RGB = 2;
    RGBW = 3;
    GENERIC = 4;
}
```

Will also add a way for hendrik to store more accurate colour information that is separate.
