### ISSUE TITLE
Potential naming issue

### ISSUE THREAD

**Issue by hputzek** [IoTPanic/pixelpusher#4]
https://github.com/IoTPanic/pixelpusher/blob/1954a2275d911fd2c72e5671dec6ab1d9487e169/protobufs/api.proto#L3

We should be clear about naming here:
If we call it "device" it has the same name as the "devices defined in software" part of my concept -> we should name one of those two things different, so:

Example:

* A "controller" is a hardware device
* A "device" (which exists only my frontend) is the mapping from the functionality of a  stripe to a part of the controller.
**Example:** "My stripe" has 144 Pixels reserved in pixeldot-1 controller's first channel from postion 10 to position 155"

**Comment by IoTPanic** [comment]
I do not mind renaming devices to controllers, but I would have thought it would be the opposite, you would want your objects to be called controllers and mine devices.

**Comment by IoTPanic** [comment]
Will be called fixtures on your end
