### ISSUE TITLE
Question: Several controller schemas needed?

### ISSUE THREAD

**Issue by hputzek** [IoTPanic/pixelpusher#5]
https://github.com/IoTPanic/pixelpusher/blob/1954a2275d911fd2c72e5671dec6ab1d9487e169/protobufs/api.proto#L18

General question: Is that abstract enough to also work for a dmx controller?
For now in the proto everything is matched for the use case of led stripes using udpx.
Do we create another kind of schema for different kinds of controllers or make this schema so abstract that it can serve for both?

**Comment by IoTPanic** [comment]
No, to you there should be almost no difference, the conversion from the pixels system to DMX should happen as a part of the backend.

**Comment by hputzek** [comment]
For stripes yes but for other dmx devices one has to think in channels. Like
"I got a fog machine which takes dmx channel 66 to trigger fog, channel 77 for fog amount, channel 88 to enable timer"

But this is not important ATM, was just meaning to ask so that it is possible to add that later.

**Comment by IoTPanic** [comment]
Resolved, will be making a connector application for DMX, and fog machines will be a 1x1 ;)
